### ISSUE TITLE
Downgrade to stock from open-wrt

### ISSUE THREAD

**Issue by Detailer** [radix007/OpenWrt-Tp-Link-C6#1]
Is it possible to downgrade to the stock firmware using the web UI method? If you've tried this then maybe a dedicated section for this in the guide will be useful.

**Comment by radix007** [comment]
> Is it possible to downgrade to the stock firmware using the web UI method? If you've tried this then maybe a dedicated section for this in the guide will be useful.

Yeah you can go back to the stock firmware  . I will add this ASAP.

**Comment by Detailer** [comment]
It would be great if you could specify the method for downgrade as well (whether through web UI or TFTP)

**Comment by radix007** [comment]
> It would be great if you could specify the method for downgrade as well (whether through web UI or TFTP)

Yeah so I am going to add a FAQ section. And one more section to roll back to to stock firmware . I think that’s the best way . Yeah to roll back you can always use the TFTP again with the oldest tp link firmware . I will do this by today .

**Comment by radix007** [comment]
I hope now your issue has been resolved i have made changes to the guide . So I am closing the issue .
