### ISSUE TITLE
Performance differences between open-wrt and stock fw

### ISSUE THREAD

**Issue by Detailer** [radix007/OpenWrt-Tp-Link-C6#2]
The official tech data on open-wrt mentions:
"WLAN Comments:5GHz WLAN has greatly reduced speed, range and stability as of openwrt 19.07"
How has been your experience been?

**Comment by radix007** [comment]
> The official tech data on open-wrt mentions:
> 
> "WLAN Comments:5GHz WLAN has greatly reduced speed, range and stability as of openwrt 19.07"
> 
> How has been your experience been?

Actually it’s pretty great for me , like when I was using the stock firmware (2.4Ghz was not working with Arch Linux idk why ) but after setting up openwrt everything is fine and speed is as it should be . I get the same speed on all my devices (120 Mmps is my avg ) . I am going to change to 200Mbps . So once that is done , I will get back to you with the performance issue , but for me it’s fine till now . I would recommended using the stable version and not the snapshot as it is testing and I had trouble with snapshot while installation .

**Comment by radix007** [comment]
> The official tech data on open-wrt mentions:
> 
> "WLAN Comments:5GHz WLAN has greatly reduced speed, range and stability as of openwrt 19.07"
> 
> How has been your experience been?

![image](https://user-images.githubusercontent.com/47687097/95646004-b2e1e480-0ae1-11eb-93c9-1c34419bfc6a.png)

This is my speed(200Mbps Plan ) . Which version of openwrt did you install , snapshot ?

**Comment by Detailer** [comment]
I am still on stock fw, was just curious about the comment mentioned on the tech data page of openwrt.

**Comment by radix007** [comment]
According to the openwrt site 5GHz WLAN has greatly reduced speed, range and stability as of openwrt 19.07.So use older version of openwrt . Refer to  WLan Comments for more info (https://openwrt.org/toh/hwdata/tp-link/tp-link_archer_c6_v2_eu) .

**Comment by Detailer** [comment]
Which version of openwrt did you install which had stable 5Ghz WLAN?

**Comment by radix007** [comment]
I haven't updated to the latest version yet . This is the version I am using right now (https://forum.openwrt.org/t/openwrt-19-07-0-first-stable-release/52186)

**Comment by Detailer** [comment]
Can you link the firmware image you used to install on Archer C6, I can't find the specific file for C6 in the above link.
Adding this information about the version you used (with a link) and a disclaimer about the 5Ghz on the newest version might be good for the guide.

**Comment by radix007** [comment]
> Can you link the firmware image you used to install on Archer C6, I can't find the specific file for C6 in the above link.

Link : https://downloads.openwrt.org/releases/19.07.0/targets/ath79/generic/openwrt-19.07.0-ath79-generic-tplink_archer-c6-v2-squashfs-factory.bin

> Adding this information about the version you used (with a link) and a disclaimer about the 5Ghz on the newest version might be good for the guide.

Yeah will add a disclaimer . Thanks For your input .

Also sorry for the late reply was busy with college stuff .

**Comment by radix007** [comment]
Also I should point out that new TP Link C6 version is available in the market with WPA3 support . They have changed the design of the C6 too .

**Comment by Malvik298** [comment]
How is your GigaBit Ethernet performance ? In Iperf I dont get more than 200Mbit/s.

**Comment by radix007** [comment]
> How is your GigaBit Ethernet performance ? In Iperf I dont get more than 200Mbit/s.

Umm , Its the same . I  just changed to 300 Mbps Plan . I am getting 300-350 Mbps . So Its pretty good . I haven't checked with iperf . But I have downloaded a lot of files from Google drive and torrent and Azure servers and AWS servers and I am getting 300Mbps . So I guess no problem till now . I should mention that I haven't updated my Openwrt. So Am way behind the updates .I hope this resolves your issue . Sorry for replying after a long time , I was quite busy with college stuff. If you have still have any doubts feel free to ask .

**Comment by NilsRo** [comment]
I am using 19.07.6 and the Wlan Performance is still poor. It is between 150-200Mbit compared with fill speed with stock firmware. Using it as a simple AP. Any hints for that? It seems a general problem like noted in the OpenWrt page of the router.

**Comment by radix007** [comment]
> I am using 19.07.6 and the Wlan Performance is still poor. It is between 150-200Mbit compared with fill speed with stock firmware. Using it as a simple AP. Any hints for that? It seems a general problem like noted in the OpenWrt page of the router.

Yeah you can not do anything about it as of now . There are still a lot of problems but you gotta comprise when it comes to security and open source . Some people face problems others don't . I haven't updated my router in a long long time and I will not do it until we get a stable build . So you just have to be patient and let the devs fix  it .

**Comment by the4anoni** [comment]
Hi

What performance does archer c6 v2 has on latest Openwrt 23?
