### ISSUE TITLE
Could not revert to stock firmware

### ISSUE THREAD

**Issue by NilsRo** [radix007/OpenWrt-Tp-Link-C6#4]
Hi,

I like to go back to stock firmware until 5Ghz issue is solved. It uploads firmware via TFTP but it does not install it. After reboot OpenWrt will start again. I tried all firmware versions available also the one you listed in the Wiki. 

![grafik](https://user-images.githubusercontent.com/51311453/107714920-6ea06400-6cce-11eb-8fe0-da2e6ac6a05f.png)

From the Logs it seems ok but I do not know how to solve this. Any ideas?

Cheers,
Nils

**Comment by NilsRo** [comment]
It solved by the way that actual snapshot firmware does not have any performance issues with WiFi anymore. But did not find a way to revert to stock firmware.

**Comment by radix007** [comment]
> It solved by the way that actual snapshot firmware does not have any performance issues with WiFi anymore. But did not find a way to revert to stock firmware.

So were you not able to revert back to the stock firmware ?

**Comment by NilsRo** [comment]
Sadly no. But I want revert because of the performance and as it solved with Snapshot it is fine. But tried everything with first firmware (your link is broken) to stripped firmware which bricked the router. But no success. OpenWRT is very sticky.

**Comment by radix007** [comment]
> Sadly no. But I want revert because of the performance and as it solved with Snapshot it is fine. But tried everything with first firmware (your link is broken) to stripped firmware which bricked the router. But no success. OpenWRT is very sticky.

Which Link ? Can you be more specific . if you want to download the tp link one you will need to copy the url and then paste it in the address bar . If you want I can upload the tp link firmware .

**Comment by NilsRo** [comment]
The link in your readme is broken for downloading the old firmware. But I did not need it anymore.

**Comment by radix007** [comment]
> The link in your readme is broken for downloading the old firmware. But I did not need it anymore.

You are talking about this right ? https://static.tp-link.com/2018/201808/20180814/Archer%20C6(EU)_V2_180627.zip . You have to copy this link and then only will the link work . Otherwise it will not work. I have mentioned that too in the guide and the reason I have just not uploaded the firmware myself is because of copyright issues .

**Comment by NilsRo** [comment]
Yes, overseen the last part of the note. It works like described with Copy & Paste. But anyhow without the performance issue I think it is not really necessary to revert to stock firmware. Perhaps only for warranty. But it is good to know.
