### ISSUE TITLE
Archer c6

### ISSUE THREAD

**Issue by kirakooo** [radix007/OpenWrt-Tp-Link-C6#5]
Dear Master!

Iam writing to you because i bricked my router.
i upgraded the stock rom to openwrt but i woud like to go back the stock.
i copied the stock firmware /temp and i execute "mtd -r write /tmp/firmware.bin firmware" in winscp.
now I can reach the router across 192.168.0.66 with tftp server and copied successfully but dont booting.
Just continously light the green power.
Can you help me?

**Comment by kirakooo** [comment]
okay. i solved the problem. :)
Just downloaded the 1.0.1 firmware from here: https://www.4shared.com/zip/sc5AY3SFiq/Archer_C6_EU__V2_180627.html
flashing with tftpd and its okay. 


Have a nice day!

**Comment by fomatica** [comment]
I've done this and it doens't work

**Comment by fomatica** [comment]
@abonyewski Plus your link is broken, the file isn't valid anymore.

![asdasd](https://user-images.githubusercontent.com/87650445/127509895-8784fdd5-edfa-44f6-a337-fd0557eb2d73.PNG)
