### ISSUE TITLE
Can't go back to OEM

### ISSUE THREAD

**Issue by fomatica** [radix007/OpenWrt-Tp-Link-C6#6]
Hi, I followed your tutorial ste-by-step and still can't manage to get back to the OEM firmware, the router resets but when I try to go to the administration page (tplinkwifi.net) it doens't go, I have to go to 192.168.1.1 and it takes me to openwrt, I've tried every version of the OEM firmware but without sucess

**Comment by kirakooo** [comment]
hi
https://github.com/radix007/OpenWrt-Tp-Link-C6/issues/5
bye

**Comment by radix007** [comment]
So you are trying to revert to stock firmware but you are having problems right. Well all you can do is try to revert to the original version 1.0 or something.This method sometimes doesn't work when you do it for the first time although if you do it 2-3 times it should work, you will have to use different oem verisons and find the right version for you. I have shared the link for version that worked for me. Note to use my verison you have to copy the link and then paste it. Then just follow the steps and it should work. if that doesn't work then your router is bricked and you will have to do it manually by opening up the router and do some soldering(youtube has some amazing content). I have frankly never tried it. If this also doesn't work then contact tp link and say your router is not working anymore (What I would do in this case would try to short the router to render it useless and so they will not be able to find out that you tried to install openwrt which might help you get a new router using your 3 year warranty). I hope you find this helpful. 
NOTE You are doing this at your own risk.

**Comment by fomatica** [comment]
SOLVED

After a few days away of the router finally found a solution on my own!!

0- Used Tftpd64 and had the firmware inside the tftpd64 folder (C:\TFTP-Root) with the file name ArcherC6v2_tp_recovery, so you should have something like C:\TFTP-Root\ArcherC6v2_tp_recovery.bin. Also used a CAT5E cable and changed the settings to only use 100Mbps Full Duplex Connection;
1- Installed OpenWRT again and made sure it was working by connecting to 192.168.1.1;
2- Changed the IP back to 192.168.0.66;
3- Installed the first firmware available ( Archer C6(EU)_V2_180627 ) but only the power light went on;
4- Updated manually to the 2nd version available ( Archer C6(EU)_V2_200402 ).
5- Waited around 5-10 minutes for the firmware to install (waited this long for every single firmware install)
